server:
  port: 8080
  error:
    include-message: always
  # 开启高性能 HTTP 压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json,text/event-stream
    min-response-size: 1024

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer-group-prefix: ${KAFKA_GROUP_PREFIX:sse-app}

  datasource:
    url: jdbc:h2:file:./data/offsetdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example: INFO
